{
 "title": "Sentinel IoT Network Monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Packets Processed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"packets\")\r\n  |> group() \r\n  |> count()"
    }
   ]
  },
  {
   "title": "Active Devices",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"devices\")\r\n  |> group(columns: [\"mac\"])\r\n  |> distinct(column: \"mac\")\r\n  |> group()\r\n  |> count()\r\n"
    }
   ]
  },
  {
   "title": "Packet Length Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"packets\" and r._field == \"length\")\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "RSSI Over Time (Packets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"packets\" and r._field == \"rssi\")\r\n  |> group(columns: [\"mac\"])\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Packet Length Distribution",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"packets\" and r._field == \"length\")\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "RSSI Over Time (Devices)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"devices\" and r._field == \"rssi\")\r\n  |> group(columns: [\"mac\"])\r\n"
    }
   ]
  },
  {
   "title": "Packets per Device",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"packets\")\r\n  |> group(columns: [\"mac\"])\r\n  |> count()\r\n  |> group()\r\n"
    }
   ]
  },
  {
   "title": "RSSI Over Time (Access Points)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"sentinel\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"access-points\" and r._field == \"rssi\")\r\n  |> group(columns: [\"mac\"])\r\n  |> group()"
    }
   ]
  }
 ]
}